### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by iaherzog** [robocup-logistics/rcll-mqtt-bridge#1]
I tried to start the rcll-mqtt-bridge with the command `./gradlew run` as it is said in the README.md. The build fails with the following excepction: 

---------------------------------------------
> Task :app:run FAILED
Exception in thread "main" org.apache.commons.cli.MissingOptionException: Missing required options: b, r, t, k
        at org.apache.commons.cli.DefaultParser.checkRequiredOptions(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:722)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:679)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:660)
        at com.rcll.java.App.main(App.java:28)

FAILURE: Build failed with an exception.
---------------------------------------------
Specifications: Ubuntu 22.04

How should I use the bridge and what is the current state of the project? Are all messages already supported and can they be sent in both ways? Could you please add more details in the README.md?

**Comment by pkohout** [comment]
Hi,
ah it seems that you misse some parameters. To be hohnes, the README is non existing yet, as long as I don't know of anyone else using it I was never really motivated to write one.  I have some spare time this week and will write a porper ReadMe + overview what is done/missing.

As far as I am aware:
All the messages from the Refbox to the Team are supported. 
Preparing of machines is supported in most case,
RobotBeacon messages are not yet implemented (Team to Refbox) are not yet implemented I think (have to check), but its not that much work to add it.

regards,
Peter

**Comment by pkohout** [comment]
@iaherzog I updated the README (also added a usage print if the program is started without required arguments). Please take a look and let me know if you have any further problems. Otherwise I would close this issue.

All the best,
Peter

**Comment by iaherzog** [comment]
Dear @pkohout , thank you very much for taking your time to improve the README. It is much clearer now and it works fine.
